#spring:
#  com.jaywu.tacos.security:
#    user:
#      name: buzz
#      password: infinity

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10
    
---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
    jndi-name: java:/comp/env/jdbc/tacoCloudDS
    schema:
      - order-schema.sql
      - taco-schema.sql
    data:
      - ingrediemts.sql
    
logging:
  level:
    tacos: WARN
    
